name: cowpay
description: Cowpay Flutter Package
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  crypto: ^3.0.1
  flutter_bloc: ^7.0.0
  equatable: ^2.0.3
  formz: ^0.4.0-nullsafety.0
  flutter_svg: ^1.0.3
  webview_flutter: ^3.0.0
  dartz:
  get_it: ^7.2.0
  api_manager:
    git:
      url: https://github.com/m0h2medtalaat/api_manager



dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  dio: ^4.0.4

flutter:
  assets:
    - assets/

